/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChat: typeof import('./src/components/AiChat.vue')['default']
    AiChatPanel: typeof import('./src/components/CodeEditor/AiChatPanel.vue')['default']
    Alert: typeof import('./src/components/ShowModal/Alert.vue')['default']
    Btn: typeof import('./src/components/Btn.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    Confirm: typeof import('./src/components/ShowModal/Confirm.vue')['default']
    DataTable: typeof import('./src/components/data-table/DataTable.vue')['default']
    DataTablePagination: typeof import('./src/components/data-table/DataTablePagination.vue')['default']
    Dropdown: typeof import('./src/components/url-input/components/Dropdown.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu/MainMenu.vue')['default']
    MenuItem: typeof import('./src/components/MainMenu/components/MenuItem.vue')['default']
    OrganizationPicker: typeof import('./src/components/MainMenu/components/OrganizationPicker.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Prompt: typeof import('./src/components/ShowModal/Prompt.vue')['default']
    RenderSfc: typeof import('./src/components/RenderSfc.vue')['default']
    RenderSfcNew: typeof import('./src/components/RenderSfcNew.vue')['default']
    ResizingTextInput: typeof import('./src/components/url-input/components/ResizingTextInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowJson: typeof import('./src/components/ShowJson.vue')['default']
    ShowModal: typeof import('./src/components/ShowModal/ShowModal.vue')['default']
    UrlInput: typeof import('./src/components/url-input/UrlInput.vue')['default']
    VueIframe: typeof import('./src/components/VueIframe/VueIframe.vue')['default']
  }
}
