import { addMigrationData } from "lib/manageSchema";
import db from "./lib/db";

export const migrations = {
    "create user table": "CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE(email))",
    "rename users to User": "ALTER TABLE users RENAME TO User",
    "create UserToken table": "CREATE TABLE IF NOT EXISTS UserToken (id INT AUTO_INCREMENT PRIMARY KEY, user INT NOT NULL, token VARCHAR(255) NOT NULL, FOREIGN KEY (user) REFERENCES User(id))",
    "add created, updated to User, datetime with microsecond precision": "ALTER TABLE User ADD COLUMN created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)",
    "add created, updated to UserToken, datetime with microsecond precision": "ALTER TABLE UserToken ADD COLUMN created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), ADD COLUMN updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)",
    "drop all tables": "DROP TABLE IF EXISTS User, UserToken",
    "recreate User table with guid varchar with collation utf8mb4_0900_bin": "CREATE TABLE IF NOT EXISTS User (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), email VARCHAR(255) NOT NULL, UNIQUE(email), passwordHash VARCHAR(255) NOT NULL)",
    "recreate UserToken table with guid varchar with collation utf8mb4_0900_bin": "CREATE TABLE IF NOT EXISTS UserToken (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), user VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL, token VARCHAR(255) NOT NULL, FOREIGN KEY (user) REFERENCES User(guid))",
    "create Workspace table": "CREATE TABLE IF NOT EXISTS Workspace (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, UNIQUE(identifier))",
    "add appleId, googleId, microsoftId, facebookId, xId, signupPlatform, city, state, country, verified to User": "ALTER TABLE User ADD COLUMN appleId VARCHAR(255), ADD COLUMN googleId VARCHAR(255), ADD COLUMN microsoftId VARCHAR(255), ADD COLUMN facebookId VARCHAR(255), ADD COLUMN xId VARCHAR(255), ADD COLUMN signupPlatform VARCHAR(255), ADD COLUMN city VARCHAR(255), ADD COLUMN state VARCHAR(255), ADD COLUMN country VARCHAR(255), ADD COLUMN verified TINYINT(1)",
    "add displayName to User": "ALTER TABLE User ADD COLUMN displayName VARCHAR(255)",
    "create Organization table": "CREATE TABLE IF NOT EXISTS Organization (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), name VARCHAR(255) NOT NULL, owner VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL, FOREIGN KEY (owner) REFERENCES User(guid))",
    'create table AuthToken': "CREATE TABLE IF NOT EXISTS AuthToken (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add token and user to AuthToken": "ALTER TABLE AuthToken ADD COLUMN token VARCHAR(255) NOT NULL, ADD COLUMN user VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL, ADD FOREIGN KEY (user) REFERENCES User(guid)",
    'create table WorkspaceFile': "CREATE TABLE IF NOT EXISTS WorkspaceFile (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table MyClass': "CREATE TABLE IF NOT EXISTS MyClass (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "drop table MyClass": "DROP TABLE IF EXISTS MyClass",
    "add workspace and path to WorkspaceFile": "ALTER TABLE WorkspaceFile ADD COLUMN workspace VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL,  ADD FOREIGN KEY (workspace) REFERENCES Workspace(guid) ON DELETE CASCADE, ADD COLUMN path TEXT NOT NULL, ADD COLUMN content LONGTEXT",
    // "set default content to ''": "ALTER TABLE WorkspaceFile MODIFY content LONGTEXT DEFAULT ''",
    "add organization to Workspace": "ALTER TABLE Workspace ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL",
    'create table UserState': "CREATE TABLE IF NOT EXISTS UserState (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add organization fk to Workspace": "ALTER TABLE Workspace ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column user to UserState': "ALTER TABLE UserState ADD COLUMN user VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column lastOrganization to UserState': "ALTER TABLE UserState ADD COLUMN lastOrganization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from UserState.user to User.guid': "ALTER TABLE UserState ADD FOREIGN KEY (user) REFERENCES User(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from UserState.lastOrganization to Organization.guid': "ALTER TABLE UserState ADD FOREIGN KEY (lastOrganization) REFERENCES Organization(guid) ON DELETE set null ON UPDATE CASCADE",
    'create table UserOrganization': "CREATE TABLE IF NOT EXISTS UserOrganization (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column user to UserOrganization': "ALTER TABLE UserOrganization ADD COLUMN user VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column organization to UserOrganization': "ALTER TABLE UserOrganization ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from UserOrganization.user to User.guid': "ALTER TABLE UserOrganization ADD FOREIGN KEY (user) REFERENCES User(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from UserOrganization.organization to User.guid': "ALTER TABLE UserOrganization ADD FOREIGN KEY (organization) REFERENCES User(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "drop foreign key on authtoken": "ALTER TABLE AuthToken DROP FOREIGN KEY AuthToken_ibfk_1",
    "add foreing key to authtoken on delete CASCADE": "ALTER TABLE AuthToken ADD FOREIGN KEY (user) REFERENCES User(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "drop foreign key UserOrganization.organization to User.guid": "ALTER TABLE UserOrganization DROP FOREIGN KEY UserOrganization_ibfk_2",
    "Drop foreign key Organization.owner": "ALTER TABLE Organization DROP FOREIGN KEY Organization_ibfk_1",
    'add foreign key from Organization.owner to User.guid': "ALTER TABLE Organization ADD FOREIGN KEY (owner) REFERENCES User(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from UserOrganization.organization to Organization.guid': "ALTER TABLE UserOrganization ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column organization to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WorkspaceFile.organization to Organization.guid': "ALTER TABLE WorkspaceFile ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table workspace_file': "CREATE TABLE IF NOT EXISTS workspace_file (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column parent to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN parent VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WorkspaceFile.parent to WorkspaceFile.guid': "ALTER TABLE WorkspaceFile ADD FOREIGN KEY (parent) REFERENCES WorkspaceFile(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column name to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN name VARCHAR(255)",
    'add column type to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN type VARCHAR(255)",
    'create table Item': "CREATE TABLE IF NOT EXISTS Item (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table Item auto_2024_25_13__06_25_033__463129': "CREATE TABLE IF NOT EXISTS Item (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to Item': "ALTER TABLE Item ADD COLUMN name VARCHAR(255)",
    'add column organization to Item': "ALTER TABLE Item ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from Item.organization to Organization.guid': "ALTER TABLE Item ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table ItemCategory': "CREATE TABLE IF NOT EXISTS ItemCategory (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemCategory auto_2024_48_15__09_48_2626__522323': "CREATE TABLE IF NOT EXISTS ItemCategory (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPage': "CREATE TABLE IF NOT EXISTS ItemPage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPage auto_2024_48_15__09_48_2727__404198': "CREATE TABLE IF NOT EXISTS ItemPage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPageItem': "CREATE TABLE IF NOT EXISTS ItemPageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPageItem auto_2024_48_15__09_48_2727__983591': "CREATE TABLE IF NOT EXISTS ItemPageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to ItemCategory': "ALTER TABLE ItemCategory ADD COLUMN name VARCHAR(255) NOT NULL",
    'add column item to ItemPageItem': "ALTER TABLE ItemPageItem ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column organization to ItemPage': "ALTER TABLE ItemPage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column organization to ItemCategory': "ALTER TABLE ItemCategory ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column itemPage to ItemPageItem': "ALTER TABLE ItemPageItem ADD COLUMN itemPage VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column organization to ItemPageItem': "ALTER TABLE ItemPageItem ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemCategory.organization to Organization.guid': "ALTER TABLE ItemCategory ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from ItemPage.organization to Organization.guid': "ALTER TABLE ItemPage ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from ItemPageItem.item to Item.guid': "ALTER TABLE ItemPageItem ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from ItemPageItem.itemPage to ItemPage.guid': "ALTER TABLE ItemPageItem ADD FOREIGN KEY (itemPage) REFERENCES ItemPage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from ItemPageItem.organization to Organization.guid': "ALTER TABLE ItemPageItem ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table Website': "CREATE TABLE IF NOT EXISTS Website (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table Website auto_2024_30_24__15_30_1616__862797': "CREATE TABLE IF NOT EXISTS Website (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table Website auto_2024_30_24__15_30_1616__241859': "CREATE TABLE IF NOT EXISTS Website (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to Website': "ALTER TABLE Website ADD COLUMN name VARCHAR(255)",
    'add column domain to Website': "ALTER TABLE Website ADD COLUMN domain VARCHAR(255)",
    'add column organization to Website': "ALTER TABLE Website ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from Website.organization to Organization.guid': "ALTER TABLE Website ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table WebsitePage': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePage auto_2024_35_25__11_35_5555__649165': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePage auto_2024_35_25__11_35_5555__119622': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN name VARCHAR(255)",
    'create table WebsitePage auto_2024_35_25__11_35_5555__275753': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'create table WebsitePage auto_2024_35_25__11_35_5555__666570': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add foreign key from WebsitePage.organization to Organization.guid': "ALTER TABLE WebsitePage ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column content to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN content JSON",
    'create table WebsitePageTemplate': "CREATE TABLE IF NOT EXISTS WebsitePageTemplate (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to WebsitePageTemplate': "ALTER TABLE WebsitePageTemplate ADD COLUMN name VARCHAR(255)",
    'add column organization to WebsitePageTemplate': "ALTER TABLE WebsitePageTemplate ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsitePageTemplate.organization to Organization.guid': "ALTER TABLE WebsitePageTemplate ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column path to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN path TEXT",
    'add column url to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN url TEXT",
    'add column website to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsitePage.website to Website.guid': "ALTER TABLE WebsitePage ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table WebsiteWebsitePage': "CREATE TABLE IF NOT EXISTS WebsiteWebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column website to WebsiteWebsitePage': "ALTER TABLE WebsiteWebsitePage ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column websitePage to WebsiteWebsitePage': "ALTER TABLE WebsiteWebsitePage ADD COLUMN websitePage VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteWebsitePage.website to Website.guid': "ALTER TABLE WebsiteWebsitePage ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteWebsitePage.websitePage to WebsitePage.guid': "ALTER TABLE WebsiteWebsitePage ADD FOREIGN KEY (websitePage) REFERENCES WebsitePage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteWebsitePage.websitePage to WebsitePage.guid auto_2024_10_02__00_10_2828__432619': "ALTER TABLE WebsiteWebsitePage ADD FOREIGN KEY (websitePage) REFERENCES WebsitePage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "Create table WebsiteWebsitePage": "CREATE TABLE IF NOT EXISTS WebsiteWebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add website, websitePage to WebsiteWebsitePage": "ALTER TABLE WebsiteWebsitePage ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column organization to WebsiteWebsitePage': "ALTER TABLE WebsiteWebsitePage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteWebsitePage.organization to Organization.guid': "ALTER TABLE WebsiteWebsitePage ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column compiled to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN compiled LONGTEXT",
    "allow null in workspace file path": "ALTER TABLE WorkspaceFile MODIFY path TEXT",
    'add column activated to Website': "ALTER TABLE Website ADD COLUMN activated TINYINT(1)",
    'add column compiledCss to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN compiledCss LONGTEXT",
    'add column compiledJs to WorkspaceFile': "ALTER TABLE WorkspaceFile ADD COLUMN compiledJs LONGTEXT",
    "drop column compiled from WorkspaceFile": "ALTER TABLE WorkspaceFile DROP COLUMN compiled",
    'create table ItemImage': "CREATE TABLE IF NOT EXISTS ItemImage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemImage auto_2024_51_21__18_51_4141__492937': "CREATE TABLE IF NOT EXISTS ItemImage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to ItemImage': "ALTER TABLE ItemImage ADD COLUMN name VARCHAR(255) NOT NULL",
    'add column organization to ItemImage': "ALTER TABLE ItemImage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemImage.organization to Organization.guid': "ALTER TABLE ItemImage ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column item to ItemImage': "ALTER TABLE ItemImage ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemImage.item to Item.guid': "ALTER TABLE ItemImage ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE RESTRICT ON UPDATE RESTRICT",
    'create table ItemProperty': "CREATE TABLE IF NOT EXISTS ItemProperty (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemProperty auto_2024_38_21__22_38_3030__840742': "CREATE TABLE IF NOT EXISTS ItemProperty (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemProperty.organization to Organization.guid': "ALTER TABLE ItemProperty ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column item to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemProperty.item to Item.guid': "ALTER TABLE ItemProperty ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column name to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN name VARCHAR(255)",
    'create table ItemPropertyType': "CREATE TABLE IF NOT EXISTS ItemPropertyType (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPropertyType auto_2024_07_22__01_07_4848__735362': "CREATE TABLE IF NOT EXISTS ItemPropertyType (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table ItemPropertyType auto_2024_07_22__01_07_4848__571495': "CREATE TABLE IF NOT EXISTS ItemPropertyType (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN name VARCHAR(255) NOT NULL",
    'add column item to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column organization to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemPropertyType.item to Item.guid': "ALTER TABLE ItemPropertyType ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from ItemPropertyType.organization to Organization.guid': "ALTER TABLE ItemPropertyType ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column inputComponent to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN inputComponent TEXT",
    'add column inputComponentCompiledCss to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN inputComponentCompiledCss TEXT",
    'add column inputComponentCompiledJs to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN inputComponentCompiledJs TEXT",
    'add column type to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN type VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemProperty.type to ItemPropertyType.guid': "ALTER TABLE ItemProperty ADD FOREIGN KEY (type) REFERENCES ItemPropertyType(guid) ON DELETE RESTRICT ON UPDATE RESTRICT",
    'add column value to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN value JSON",
    'add column size to ItemImage': "ALTER TABLE ItemImage ADD COLUMN size BIGINT",
    'add column uploaded to ItemImage': "ALTER TABLE ItemImage ADD COLUMN uploaded TINYINT(1)",
    'add column description to ItemImage': "ALTER TABLE ItemImage ADD COLUMN description TEXT",
    'add column contentType to ItemImage': "ALTER TABLE ItemImage ADD COLUMN contentType TEXT",
    'add column url to WebsiteWebsitePage': "ALTER TABLE WebsiteWebsitePage ADD COLUMN url TEXT",
    "drop website page url": "ALTER TABLE WebsitePage DROP COLUMN url",
    "add url index to WebsiteWebsitePage": "ALTER TABLE WebsiteWebsitePage ADD INDEX (url(255))",
    "remove path from WebsitePage": "ALTER TABLE WebsitePage DROP COLUMN path",
    'add column defaultUrl to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN defaultUrl TEXT",
    'add column addToAllSites to WebsitePage': "ALTER TABLE WebsitePage ADD COLUMN addToAllSites TINYINT(1)",
    "drop column defaultUrl on WebsitePage": "ALTER TABLE WebsitePage DROP COLUMN defaultUrl",
    "add column defaultUrl on WebsitePage, json": "ALTER TABLE WebsitePage ADD COLUMN defaultUrl JSON",
    "delete WebsiteWebsitePage.url from WebsiteWebsitePage table": "ALTER TABLE WebsiteWebsitePage DROP COLUMN url",
    "add url to WebsiteWebsitePage as json": "ALTER TABLE WebsiteWebsitePage ADD COLUMN url JSON",
    "delete WebsiteWebsitePage.url from WebsiteWebsitePage table again": "ALTER TABLE WebsiteWebsitePage DROP COLUMN url",
    'add column url to WebsiteWebsitePage auto_2024_40_27__17_40_5757__483434': "ALTER TABLE WebsiteWebsitePage ADD COLUMN url TEXT",
    "delete WebsiteWebsitePage.url from WebsiteWebsitePage table againx2": "ALTER TABLE WebsiteWebsitePage DROP COLUMN url",
    'add column url to WebsiteWebsitePage auto_2024_41_27__17_41_2929__626118': "ALTER TABLE WebsiteWebsitePage ADD COLUMN url JSON",
    'create table Upload': "CREATE TABLE IF NOT EXISTS Upload (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table Upload auto_2024_06_29__21_06_088__222749': "CREATE TABLE IF NOT EXISTS Upload (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table Upload auto_2024_06_29__21_06_099__998879': "CREATE TABLE IF NOT EXISTS Upload (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to Upload': "ALTER TABLE Upload ADD COLUMN name BIGINT",
    'add column organization to Upload': "ALTER TABLE Upload ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from Upload.organization to Organization.guid': "ALTER TABLE Upload ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from Upload.organization to Organization.guid auto_2024_06_29__21_06_5151__587987': "ALTER TABLE Upload ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column size to Upload': "ALTER TABLE Upload ADD COLUMN size BIGINT",
    'add column description to Upload': "ALTER TABLE Upload ADD COLUMN description TEXT",
    "change name on upload to text": "ALTER TABLE Upload MODIFY COLUMN name TEXT",
    'add column contentType to Upload': "ALTER TABLE Upload ADD COLUMN contentType VARCHAR(255)",
    'add column uploaded to Upload': "ALTER TABLE Upload ADD COLUMN uploaded TINYINT(1)",
    'add column cloudStorageKey to Upload': "ALTER TABLE Upload ADD COLUMN cloudStorageKey TEXT",
    'add column cloudStorageName to Upload': "ALTER TABLE Upload ADD COLUMN cloudStorageName TEXT",
    'add column key to Upload': "ALTER TABLE Upload ADD COLUMN `key` VARCHAR(255)",
    'add column objectId to Upload': "ALTER TABLE Upload ADD COLUMN objectId VARCHAR(255)",
    'create table OrderData': "CREATE TABLE IF NOT EXISTS OrderData (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column postalCode to OrderData': "ALTER TABLE OrderData ADD COLUMN postalCode VARCHAR(35)",
    'add column shoppingCart to OrderData': "ALTER TABLE OrderData ADD COLUMN shoppingCart JSON",
    'add column email to OrderData': "ALTER TABLE OrderData ADD COLUMN email VARCHAR(255)",
    'add column deliveryAddress1 to OrderData': "ALTER TABLE OrderData ADD COLUMN deliveryAddress1 TEXT",
    'add column deliveryAddress2 to OrderData': "ALTER TABLE OrderData ADD COLUMN deliveryAddress2 TEXT",
    'add column website to OrderData': "ALTER TABLE OrderData ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column region to OrderData': "ALTER TABLE OrderData ADD COLUMN region VARCHAR(255)",
    'add column phone to OrderData': "ALTER TABLE OrderData ADD COLUMN phone VARCHAR(25)",
    'add column city to OrderData': "ALTER TABLE OrderData ADD COLUMN city TEXT",
    'add foreign key from OrderData.website to Website.guid': "ALTER TABLE OrderData ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE RESTRICT ON UPDATE CASCADE",
    'add column organization to OrderData': "ALTER TABLE OrderData ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from OrderData.organization to Organization.guid': "ALTER TABLE OrderData ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE RESTRICT ON UPDATE CASCADE",
    'add column total to OrderData': "ALTER TABLE OrderData ADD COLUMN total DECIMAL(12, 2)",
    'add column subtotal to OrderData': "ALTER TABLE OrderData ADD COLUMN subtotal DECIMAL(12, 2)",
    'add column tax to OrderData': "ALTER TABLE OrderData ADD COLUMN tax DECIMAL(12, 2)",
    'add column cart to OrderData': "ALTER TABLE OrderData ADD COLUMN cart JSON",
    "drop column shoppingCart from OrderData": "ALTER TABLE OrderData DROP COLUMN shoppingCart",
    'add column deliveryAddressLine1 to OrderData': "ALTER TABLE OrderData ADD COLUMN deliveryAddressLine1 TEXT",
    'add column deliveryAddressLine2 to OrderData': "ALTER TABLE OrderData ADD COLUMN deliveryAddressLine2 TEXT",
    "drop column deliveryAddress1 AND 2 from OrderData": "ALTER TABLE OrderData DROP COLUMN deliveryAddress1, DROP COLUMN deliveryAddress2",
    'add column details to OrderData': "ALTER TABLE OrderData ADD COLUMN details JSON",
    'create table PaypalOrder': "CREATE TABLE IF NOT EXISTS PaypalOrder (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table PaypalOrder auto_2024_14_10__18_14_2525__252446': "CREATE TABLE IF NOT EXISTS PaypalOrder (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table PaypalOrder auto_2024_14_10__18_14_2525__134428': "CREATE TABLE IF NOT EXISTS PaypalOrder (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table PaypalOrder auto_2024_14_10__18_14_2626__249362': "CREATE TABLE IF NOT EXISTS PaypalOrder (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column paypalId to PaypalOrder': "ALTER TABLE PaypalOrder ADD COLUMN paypalId VARCHAR(30)",
    'add column status to PaypalOrder': "ALTER TABLE PaypalOrder ADD COLUMN status VARCHAR(30)",
    'add column cart to PaypalOrder': "ALTER TABLE PaypalOrder ADD COLUMN cart JSON",
    'add column payload to PaypalOrder': "ALTER TABLE PaypalOrder ADD COLUMN payload JSON",
    'drop column cart from PaypalOrder': "ALTER TABLE PaypalOrder DROP COLUMN cart",
    'create table WebsiteItem': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5252__590756': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__928633': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__875468': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__506834': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__591487': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column item to WebsiteItem': "ALTER TABLE WebsiteItem ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__889940': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to WebsiteItem': "ALTER TABLE WebsiteItem ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column website to WebsiteItem': "ALTER TABLE WebsiteItem ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__551216': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsiteItem auto_2024_31_14__01_31_5353__412725': "CREATE TABLE IF NOT EXISTS WebsiteItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add foreign key from WebsiteItem.item to Item.guid': "ALTER TABLE WebsiteItem ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteItem.organization to Organization.guid': "ALTER TABLE WebsiteItem ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteItem.website to Website.guid': "ALTER TABLE WebsiteItem ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column website to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemProperty.website to Website.guid': "ALTER TABLE ItemProperty ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column websiteItem to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN websiteItem VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from ItemProperty.websiteItem to WebsiteItem.guid': "ALTER TABLE ItemProperty ADD FOREIGN KEY (websiteItem) REFERENCES WebsiteItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column addToAllSites to WebsiteItem': "ALTER TABLE WebsiteItem ADD COLUMN addToAllSites TINYINT(1)",
    'add column addToAllSites to Item': "ALTER TABLE Item ADD COLUMN addToAllSites TINYINT(1)",
    "drop fk ALTER TABLE ultracode.ItemProperty DROP FOREIGN KEY itemproperty_ibfk_5": "ALTER TABLE ItemProperty DROP FOREIGN KEY itemproperty_ibfk_5",
    "drop column WebsiteItem from ItemProperty": "ALTER TABLE ItemProperty DROP COLUMN websiteItem",
    'add column orderData to PaypalOrder': "ALTER TABLE PaypalOrder ADD COLUMN orderData JSON",
    'add column deliveryDate to OrderData': "ALTER TABLE OrderData ADD COLUMN deliveryDate DATE",
    'add column delivaryTime to OrderData': "ALTER TABLE OrderData ADD COLUMN delivaryTime TIME(0)",
    'add column installationDate to OrderData': "ALTER TABLE OrderData ADD COLUMN installationDate DATE",
    'add column installationTime to OrderData': "ALTER TABLE OrderData ADD COLUMN installationTime TIME(0)",
    "drop table WebsitePageTemplate": "DROP TABLE WebsitePageTemplate",
    "rename table WebsitePage to WebsitePageTemplate": "RENAME TABLE WebsitePage to WebsitePageTemplate",
    "rename table WebsiteWebsitePage to WebsiteWebsitePageTemplate": "RENAME TABLE WebsiteWebsitePage to WebsiteWebsitePageTemplate",
    'create table WebsitePageItem': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__386669': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__51779': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__566762': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__155183': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__514103': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column websitePageItem to WebsitePageItem': "ALTER TABLE WebsitePageItem ADD COLUMN websitePageItem VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__523501': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'create table WebsitePage again': "CREATE TABLE IF NOT EXISTS WebsitePage (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), identifier VARCHAR(255))",
    "add organization to WebsitePage again": "ALTER TABLE WebsitePage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column websitePage to WebsitePageItem': "ALTER TABLE WebsitePageItem ADD COLUMN websitePage VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'create table WebsitePageItem auto_2024_30_19__14_30_3030__373262': "CREATE TABLE IF NOT EXISTS WebsitePageItem (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to WebsitePageItem': "ALTER TABLE WebsitePageItem ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsitePageItem.websitePage to WebsitePage.guid': "ALTER TABLE WebsitePageItem ADD FOREIGN KEY (websitePage) REFERENCES WebsitePage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsitePageItem.organization to Organization.guid': "ALTER TABLE WebsitePageItem ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsitePageItem.websitePageItem to WebsitePageItem.guid': "ALTER TABLE WebsitePageItem ADD FOREIGN KEY (websitePageItem) REFERENCES WebsitePageItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column item to WebsitePageItem': "ALTER TABLE WebsitePageItem ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsitePageItem.item to Item.guid': "ALTER TABLE WebsitePageItem ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add unique index to WebsitePage.identifier': "ALTER TABLE WebsitePage ADD UNIQUE INDEX (identifier)",
    'add column uploads to Item': "ALTER TABLE Item ADD COLUMN uploads JSON",
    // 'add column property to ItemProperty': "ALTER TABLE ItemProperty ADD COLUMN property VARCHAR(255) NOT NULL",
    'add column isTest to Website': "ALTER TABLE Website ADD COLUMN isTest TINYINT(1)",
    // 'add foreign key from WebsitePage.organization to Organization.guid auto_2024_22_05__01_22_2424__536626': "ALTER TABLE WebsitePage ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column websitePageTemplate to WebsiteWebsitePageTemplate': "ALTER TABLE WebsiteWebsitePageTemplate ADD COLUMN websitePageTemplate VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteWebsitePageTemplate.websitePageTemplate to WebsitePageTemplate.guid': "ALTER TABLE WebsiteWebsitePageTemplate ADD FOREIGN KEY (websitePageTemplate) REFERENCES WebsitePageTemplate(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'make path=name on WorkspaceFile': 'UPDATE WorkspaceFile SET path=name',
    'add column builtIn to ItemPropertyType': "ALTER TABLE ItemPropertyType ADD COLUMN builtIn TINYINT(1)",
    "create BatteryInfo table": "CREATE TABLE IF NOT EXISTS BatteryInfo (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, UNIQUE(identifier))",
    "add columns to BatteryInfo": "ALTER TABLE BatteryInfo ADD COLUMN carIdentifier TEXT, ADD INDEX (carIdentifier(255)), ADD COLUMN value VARCHAR(255)",
    "create BatteryInfoQuery table": "CREATE TABLE IF NOT EXISTS BatteryInfoQuery (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, UNIQUE(identifier))",
    "add columns to BatteryInfoQuery": "ALTER TABLE BatteryInfoQuery ADD COLUMN ipAddress VARCHAR(255), ADD INDEX (ipAddress)",
    "add bciGroup, cca to BatteryInfo": "ALTER TABLE BatteryInfo ADD COLUMN bciGroup VARCHAR(200), ADD COLUMN cca BIGINT",
    // 'DROP carIdentifier INDEX ON BatteryInfo': "ALTER TABLE BatteryInfo DROP INDEX (carIdentifier, value)",
    // "add column carIdentifier": "ALTER TABLE BatteryInfo ADD COLUMN carIdentifier TEXT",
    "add unique idx carIdentifier": "ALTER TABLE BatteryInfo ADD UNIQUE INDEX (carIdentifier(255))",
    "drop identifier from BatteryInfo": "ALTER TABLE BatteryInfo DROP INDEX identifier, DROP COLUMN identifier",
    "drop identifier from BatteryInfoQuery": "ALTER TABLE BatteryInfoQuery DROP INDEX identifier, DROP COLUMN identifier",
    "index created, ip on BatteryInfoQuery": "ALTER TABLE BatteryInfoQuery ADD INDEX (created, ipAddress)",
    "drop name from BatteryInfo": "ALTER TABLE BatteryInfo DROP COLUMN name",
    "drop name from BatteryInfoQuery": "ALTER TABLE BatteryInfoQuery DROP COLUMN name",
    "create index on workspace,path on WorkspaceFile": "ALTER TABLE WorkspaceFile ADD UNIQUE INDEX (workspace,path(512))",
    "delete Decimal and Integer ItemPropertyType": "DELETE FROM ItemPropertyType WHERE name IN ('Decimal','Integer');",
    "create TlsCertificate table": "CREATE TABLE IF NOT EXISTS TlsCertificate (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to TlsCertificate': "ALTER TABLE TlsCertificate ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from TlsCertificate to Organization.guid': "ALTER TABLE TlsCertificate ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add domain, certificate, expire, organization to TlsCertificate": "ALTER TABLE TlsCertificate ADD COLUMN domain TEXT, ADD INDEX (organization, domain(255)), ADD COLUMN certificate TEXT, ADD COLUMN expires DATETIME",
    'create table WebsiteDomain': "CREATE TABLE IF NOT EXISTS WebsiteDomain (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column organization to WebsiteDomain': "ALTER TABLE WebsiteDomain ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add website to WebsiteDomain": "ALTER TABLE WebsiteDomain ADD COLUMN website  VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteDomain.website to Website.guid': "ALTER TABLE WebsiteDomain ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add column domainm to WebsiteDomain": "ALTER TABLE WebsiteDomain ADD column domain TEXT",
    "add uinque index on WebsiteDomain.domain": "ALTER TABLE WebsiteDomain ADD UNIQUE INDEX (domain(512))",
    "index domain on Website": "ALTER TABLE Website ADD UNIQUE INDEX (domain)",
    'add column key to TlsCertificate': "ALTER TABLE TlsCertificate ADD COLUMN privateKey TEXT",
    'add foreign key from WebsiteDomain.organization to Organization.guid': "ALTER TABLE WebsiteDomain ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteDomain.organization to Organization.guid auto_2024_20_14__00_20_4242__695053': "ALTER TABLE WebsiteDomain ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'create table WebsiteProperty': "CREATE TABLE IF NOT EXISTS WebsiteProperty (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    'add column name to WebsiteProperty': "ALTER TABLE WebsiteProperty ADD COLUMN name VARCHAR(255) NOT NULL",
    "add organization to WebsiteProperty": "ALTER TABLE WebsiteProperty ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add website to WebsiteProperty": "ALTER TABLE WebsiteProperty ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteProperty.organization to Organization.guid': "ALTER TABLE WebsiteProperty ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add foreign key from WebsiteProperty.website to WebsiteItem.guid': "ALTER TABLE WebsiteProperty ADD FOREIGN KEY (website) REFERENCES WebsiteItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    'add column item to WebsiteProperty': "ALTER TABLE WebsiteProperty ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add column value to WebsiteProperty': "ALTER TABLE WebsiteProperty ADD COLUMN value JSON",
    'add column type to WebsiteProperty': "ALTER TABLE WebsiteProperty ADD COLUMN type VARCHAR(255) COLLATE utf8mb4_0900_bin",
    'add foreign key from WebsiteProperty.type to ItemPropertyType.guid': "ALTER TABLE WebsiteProperty ADD FOREIGN KEY (type) REFERENCES ItemPropertyType(guid) ON DELETE RESTRICT ON UPDATE RESTRICT",
    'add foreign key from WebsiteProperty.item to Item.guid': "ALTER TABLE WebsiteProperty ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "drop foreign key item on WebsiteProperty": "ALTER TABLE WebsiteProperty DROP FOREIGN KEY websiteproperty_ibfk_4",
    "drop item from WebsiteProperty": "ALTER TABLE WebsiteProperty DROP COLUMN item",
    "drop websitewebsitepagetemplate_ibfk_11 from WebsiteWebsitePageTemplate": "select now()",
    "add fk WebsiteWebsitePageTemplate.websitePageTemplate": "ALTER TABLE WebsiteWebsitePageTemplate ADD FOREIGN KEY (websitePageTemplate) REFERENCES WebsitePageTemplate(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "drop websitewebsitepagetemplate_ibfk_12 from WebsiteWebsitePageTemplate": "select now()",
    "add urlOverride bit to WebsitePageTemplate": "ALTER TABLE WebsitePageTemplate ADD COLUMN urlOverride TINYINT(1)",
    "remove urlOverride from WebsitePageTemplate": "ALTER TABLE WebsitePageTemplate DROP COLUMN urlOverride",
    "add urlOverride to WebsiteWebsitePageTemplate": "ALTER TABLE WebsiteWebsitePageTemplate ADD COLUMN urlOverride TINYINT(1)",
    "add quantity to BatteryInfo": "ALTER TABLE BatteryInfo ADD COLUMN quantity INT",
    "create Table ItemImport": "CREATE TABLE IF NOT EXISTS ItemImport (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add organization, item to ItemImport with foreign keys": "ALTER TABLE ItemImport ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD COLUMN item VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add foreign key from ItemImport.organization to Organization.guid": "ALTER TABLE ItemImport ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add foreign key from ItemImport.item to Item.guid": "ALTER TABLE ItemImport ADD FOREIGN KEY (item) REFERENCES Item(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "make name unique on ItemPropertyType organization, name": "ALTER TABLE ItemPropertyType ADD UNIQUE INDEX (organization, name)",
    "create table ItemImportTask": "CREATE TABLE IF NOT EXISTS ItemImportTask (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add organization to ItemImportTask": "ALTER TABLE ItemImportTask ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add foreign key from ItemImportTask.organization to Organization.guid": "ALTER TABLE ItemImportTask ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add itemImportTask to ItemImport": "ALTER TABLE ItemImport ADD COLUMN itemImportTask VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (itemImportTask) REFERENCES ItemImportTask(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "create table ItemImportBackup": "CREATE TABLE IF NOT EXISTS ItemImportBackup (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add itemImport to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN itemImport VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (itemImport) REFERENCES ItemImport(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add table to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN tableName VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add data to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN data JSON",
    "add organization to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add websitePage to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN websitePage VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websitePage) REFERENCES WebsitePage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add websitePageItem to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN websitePageItem VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websitePageItem) REFERENCES WebsitePageItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add websiteItem to ItemImportBackup": "ALTER TABLE ItemImportBackup ADD COLUMN websiteItem VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websiteItem) REFERENCES WebsiteItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "remove websiteItem from ItemImportBackup": "ALTER TABLE ItemImportBackup DROP FOREIGN KEY itemimportbackup_ibfk_5, DROP COLUMN websiteItem",
    "remove websitePageItem from ItemImportBackup": "ALTER TABLE ItemImportBackup DROP FOREIGN KEY itemimportbackup_ibfk_4, DROP COLUMN websitePageItem",
    "remove websitePage from ItemImportBackup": "ALTER TABLE ItemImportBackup DROP FOREIGN KEY itemimportbackup_ibfk_3, DROP COLUMN websitePage",
    "add websitePage to ItemImport": "ALTER TABLE ItemImport ADD COLUMN websitePage VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websitePage) REFERENCES WebsitePage(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add websitePageItem to ItemImport": "ALTER TABLE ItemImport ADD COLUMN websitePageItem VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websitePageItem) REFERENCES WebsitePageItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add websiteItem to ItemImport": "ALTER TABLE ItemImport ADD COLUMN websiteItem VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (websiteItem) REFERENCES WebsiteItem(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add rolledBack, recordsCount, completed to ItemImportTask": "ALTER TABLE ItemImportTask ADD COLUMN rolledBack TINYINT(1), ADD COLUMN recordsCount BIGINT, ADD COLUMN completed TINYINT(1)",
    "create table DkimKey": "CREATE TABLE IF NOT EXISTS DkimKey (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add columns to DkimKey": "ALTER TABLE DkimKey ADD COLUMN privateKey TEXT, ADD COLUMN publicKey TEXT",
    "add website to DkimKey": "ALTER TABLE DkimKey ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add domain to DkimKey": "ALTER TABLE DkimKey ADD COLUMN domain VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "convert WorkspaceFile.content to MEDIUMBLOB": "ALTER TABLE WorkspaceFile MODIFY COLUMN content MEDIUMBLOB",
    "add 'compliled' mediumblob to WorkspaceFile": "ALTER TABLE WorkspaceFile ADD COLUMN compiled MEDIUMBLOB",
    "create table WorkspaceFileDependency": "CREATE TABLE IF NOT EXISTS WorkspaceFileDependency (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add columns to WorkspaceFileDependency": "ALTER TABLE WorkspaceFileDependency ADD COLUMN workspaceFile VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (workspaceFile) REFERENCES WorkspaceFile(guid) ON DELETE CASCADE ON UPDATE CASCADE, ADD COLUMN path TEXT, ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "rename lastOrganization currentOrganization on UserState": "ALTER TABLE UserState CHANGE lastOrganization currentOrganization VARCHAR(255) COLLATE utf8mb4_0900_bin",
    "add organization not null to WebsitePage": "SELECT NOW()",//"ALTER TABLE WebsitePage ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add workspace to WorkspaceFileDependency": "ALTER TABLE WorkspaceFileDependency ADD COLUMN workspace VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (workspace) REFERENCES Workspace(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "add importText to WorkspaceFileDependency": "ALTER TABLE WorkspaceFileDependency ADD COLUMN importText TEXT",
    "add metadata to Upload": "ALTER TABLE Upload ADD COLUMN metadata JSON",
    "add systemUse to ItemProperty": "ALTER TABLE ItemProperty ADD COLUMN systemUse TINYINT(1)",
    "create table OrganizationInvitation": "CREATE TABLE IF NOT EXISTS OrganizationInvitation (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add columns to OrganizationInvitation": "ALTER TABLE OrganizationInvitation ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE, ADD COLUMN email TEXT, ADD INDEX (email(100)), ADD COLUMN name TEXT, ADD COLUMN token VARCHAR(100), ADD INDEX (token)",
    "add inviteSent to OrganizationInvitation": "ALTER TABLE OrganizationInvitation ADD COLUMN inviteSent TINYINT(1)",
    "Create table StripeSettings": "CREATE TABLE IF NOT EXISTS StripeSettings (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), stripeAccountId VARCHAR(255) NOT NULL, complete TINYINT(1), organization VARCHAR(255) COLLATE utf8mb4_0900_bin NOT NULL, FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE)",
    "rename ItemProperty.value JSON value to ItemProperty.value JSON data": `UPDATE ItemProperty 
        SET value = JSON_OBJECT('data', JSON_EXTRACT(value, '$.value')) 
        WHERE JSON_EXTRACT(value, '$.value') IS NOT NULL`,
    "make workspaceFile.path case sensitive collation utf8mb4_0900_as_cs": "ALTER TABLE WorkspaceFile MODIFY COLUMN path TEXT COLLATE utf8mb4_0900_as_cs",
    "create table Purchase": "CREATE TABLE IF NOT EXISTS Purchase (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add columns to Purchase": "ALTER TABLE Purchase ADD COLUMN cart JSON, ADD COLUMN details JSON, ADD COLUMN state VARCHAR(255), ADD INDEX (state), ADD COLUMN stripeSessionId VARCHAR(255), ADD COLUMN website VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (website) REFERENCES Website(guid) ON DELETE SET NULL ON UPDATE CASCADE, ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE RESTRICT ON UPDATE CASCADE",
    "add total @decimal({ totalDigits: 10, decimalDigits: 2 }) to Purchase": "ALTER TABLE Purchase ADD COLUMN total DECIMAL(10, 2)",
    "convert totalDigits to 14 on Purchase.total": "ALTER TABLE Purchase MODIFY COLUMN total DECIMAL(14, 2)",

    "create table AppleSettings": "CREATE TABLE IF NOT EXISTS AppleSettings (guid VARCHAR(255) PRIMARY KEY COLLATE utf8mb4_0900_bin, created DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6), updated DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6))",
    "add columns to AppleSettings": "ALTER TABLE AppleSettings ADD COLUMN appleDomainAssociationFile VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD COLUMN organization VARCHAR(255) COLLATE utf8mb4_0900_bin, ADD FOREIGN KEY (organization) REFERENCES Organization(guid) ON DELETE CASCADE ON UPDATE CASCADE",
    "make stripeAccountId nullable": "ALTER TABLE StripeSettings MODIFY COLUMN stripeAccountId VARCHAR(255) NULL",
    "add pathParts to WorkspaceFile": "ALTER TABLE WorkspaceFile ADD COLUMN pathParts JSON",
    "add pathParts{1-15} generated always to WorkspaceFile": addPathColumns(),
    "dropt pathParts{1-15} from WorkspaceFile": dropPathColumns(),
    "add pathParts{1-15} generated always to WorkspaceFile again": addPathColumns(),
    "add runsUntrustedCode to Organization": "ALTER TABLE Organization ADD COLUMN runsUntrustedCode TINYINT(1) DEFAULT 0",
}
function dropPathColumns() {
    let sql = `ALTER TABLE WorkspaceFile `;
    let parts = []
    for (let i = 1; i <= 15; i++) {
        parts.push(`DROP COLUMN pathPart${i}`);
    }
    sql += parts.join(", ");
    return sql;
}
function addPathColumns() {
    let sql = `ALTER TABLE WorkspaceFile `;
    let parts = []
    for (let i = 1; i <= 15; i++) {
        parts.push(`ADD COLUMN pathPart${i} VARCHAR(255) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(pathParts, '$[${i-1}]'))) VIRTUAL`);
    }
    sql += parts.join(", ");
    return sql;
}

export async function runMigrations() {
    // create migrations table if not exists
    await db.execute(`CREATE TABLE IF NOT EXISTS migrations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    )`);
    let existingMigrations = await db.query(`SELECT * FROM migrations`);
    for (let migration in migrations) {
        if (!existingMigrations.find((m) => m.name === migration)) {
            await db.transaction(async (db) => {
                console.log("running migration", migration);
                try {
                    await db.execute(migrations[migration], [], { disableScanForChanges: true });
                    await db.execute(`INSERT INTO migrations (name) VALUES (?)`, [migration], { disableScanForChanges: true });
                } catch (err) {
                    console.error("error running migration", err)
                    process.exit();
                    await db.execute(`DELETE FROM migrations WHERE name = ?`, [migration], { disableScanForChanges: true });
                }
                await db.execute(`INSERT INTO migrations (name) VALUES (?)`, [migration], { disableScanForChanges: true });
            });
        }
    }
    addMigrationData.initialMigrationsComplete = true;
}